// smarthr/app/applicant/profile/page.tsx
"use client";

import { useEffect, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { getUserInfo, updateUserInfo } from "@/lib/api";
import { toast } from "sonner";
import { User, Mail, Phone, Building, Calendar, Edit2, Save, X } from "lucide-react";

interface UserInfo {
  id: string;
  name: string;
  email: string;
  phone?: string;
  company?: string;
  role: string;
  createdAt: string;
}

export default function ApplicantProfilePage() {
  const [userInfo, setUserInfo] = useState<UserInfo | null>(null);
  const [isEditing, setIsEditing] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const [editForm, setEditForm] = useState({
    name: "",
    phone: "",
    email: "",
  });

  useEffect(() => {
    loadUserInfo();
  }, []);

  const loadUserInfo = async () => {
    try {
      setIsLoading(true);
      const data = await getUserInfo();
      setUserInfo(data);
      setEditForm({
        name: data.name || "",
        phone: data.phone || "",
        email: data.email || "",
      });
    } catch (error) {
      toast.error("加载用户信息失败");
    } finally {
      setIsLoading(false);
    }
  };

  const handleSave = async () => {
    try {
      setIsSaving(true);
      await updateUserInfo({
        name: editForm.name,
        phone: editForm.phone,
        email: editForm.email,
      });
      toast.success("个人信息更新成功");
      setIsEditing(false);
      loadUserInfo();
    } catch (error) {
      toast.error("更新失败，请重试");
    } finally {
      setIsSaving(false);
    }
  };

  const handleCancel = () => {
    setIsEditing(false);
    if (userInfo) {
      setEditForm({
        name: userInfo.name || "",
        phone: userInfo.phone || "",
        email: userInfo.email || "",
      });
    }
  };

  if (isLoading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mx-auto"></div>
          <p className="mt-2 text-gray-600">加载中...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50 py-8 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto">
        {/* 页面标题 */}
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-gray-900">个人中心</h1>
          <p className="mt-2 text-gray-600">管理您的个人信息和账户设置</p>
        </div>

        {/* 个人信息卡片 */}
        <Card className="mb-6">
          <CardHeader className="flex flex-row items-center justify-between">
            <div>
              <CardTitle className="text-xl flex items-center gap-2">
                <User className="h-5 w-5" />
                基本信息
              </CardTitle>
              <CardDescription>查看和编辑您的个人资料</CardDescription>
            </div>
            {!isEditing && (
              <Button
                variant="outline"
                size="sm"
                onClick={() => setIsEditing(true)}
                className="flex items-center gap-1"
              >
                <Edit2 className="h-4 w-4" />
                编辑
              </Button>
            )}
          </CardHeader>
          <CardContent>
            {isEditing ? (
              <div className="space-y-4">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="name">
                      姓名 <span className="text-red-500">*</span>
                    </Label>
                    <Input
                      id="name"
                      value={editForm.name}
                      onChange={(e) =>
                        setEditForm({ ...editForm, name: e.target.value })
                      }
                      placeholder="请输入姓名"
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="phone">手机号码</Label>
                    <Input
                      id="phone"
                      value={editForm.phone}
                      onChange={(e) =>
                        setEditForm({ ...editForm, phone: e.target.value })
                      }
                      placeholder="请输入手机号码"
                    />
                  </div>
                </div>
                <div className="space-y-2">
                  <Label htmlFor="email">
                    邮箱 <span className="text-red-500">*</span>
                  </Label>
                  <Input
                    id="email"
                    type="email"
                    value={editForm.email}
                    onChange={(e) =>
                      setEditForm({ ...editForm, email: e.target.value })
                    }
                    placeholder="请输入邮箱地址"
                  />
                </div>
                <div className="flex justify-end gap-3 pt-4">
                  <Button
                    variant="outline"
                    onClick={handleCancel}
                    disabled={isSaving}
                    className="flex items-center gap-1"
                  >
                    <X className="h-4 w-4" />
                    取消
                  </Button>
                  <Button
                    onClick={handleSave}
                    disabled={isSaving}
                    className="flex items-center gap-1"
                  >
                    <Save className="h-4 w-4" />
                    {isSaving ? "保存中..." : "保存"}
                  </Button>
                </div>
              </div>
            ) : (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-full bg-blue-100 flex items-center justify-center">
                    <User className="h-5 w-5 text-blue-600" />
                  </div>
                  <div>
                    <p className="text-sm text-gray-500">姓名</p>
                    <p className="font-medium text-gray-900">
                      {userInfo?.name || "-"}
                    </p>
                  </div>
                </div>
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-full bg-green-100 flex items-center justify-center">
                    <Mail className="h-5 w-5 text-green-600" />
                  </div>
                  <div>
                    <p className="text-sm text-gray-500">邮箱</p>
                    <p className="font-medium text-gray-900">
                      {userInfo?.email || "-"}
                    </p>
                  </div>
                </div>
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-full bg-purple-100 flex items-center justify-center">
                    <Phone className="h-5 w-5 text-purple-600" />
                  </div>
                  <div>
                    <p className="text-sm text-gray-500">手机号码</p>
                    <p className="font-medium text-gray-900">
                      {userInfo?.phone || "-"}
                    </p>
                  </div>
                </div>
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-full bg-orange-100 flex items-center justify-center">
                    <Calendar className="h-5 w-5 text-orange-600" />
                  </div>
                  <div>
                    <p className="text-sm text-gray-500">注册时间</p>
                    <p className="font-medium text-gray-900">
                      {userInfo?.createdAt
                        ? new Date(userInfo.createdAt).toLocaleDateString(
                            "zh-CN"
                          )
                        : "-"}
                    </p>
                  </div>
                </div>
              </div>
            )}
          </CardContent>
        </Card>

        {/* 账户安全卡片 */}
        <Card>
          <CardHeader>
            <CardTitle className="text-xl flex items-center gap-2">
              <Building className="h-5 w-5" />
              账户安全
            </CardTitle>
            <CardDescription>管理您的账户安全设置</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              <div className="flex items-center justify-between py-3 border-b border-gray-100">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-full bg-blue-100 flex items-center justify-center">
                    <Mail className="h-5 w-5 text-blue-600" />
                  </div>
                  <div>
                    <p className="font-medium text-gray-900">邮箱验证</p>
                    <p className="text-sm text-gray-500">
                      {userInfo?.email ? "已验证" : "未验证"}
                    </p>
                  </div>
                </div>
                <Button variant="outline" size="sm">
                  修改邮箱
                </Button>
              </div>
              <div className="flex items-center justify-between py-3">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-full bg-green-100 flex items-center justify-center">
                    <Building className="h-5 w-5 text-green-600" />
                  </div>
                  <div>
                    <p className="font-medium text-gray-900">密码</p>
                    <p className="text-sm text-gray-500">建议定期更换密码</p>
                  </div>
                </div>
                <Button variant="outline" size="sm">
                  修改密码
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

// frontend/src/views/jobseeker/profile/index.vue
<template>
  <div class="profile-container">
    <div class="profile-header">
      <h1>个人中心</h1>
      <p class="subtitle">管理您的个人信息和账户设置</p>
    </div>

    <!-- 加载状态 -->
    <div v-if="isLoading" class="loading-container">
      <el-skeleton :rows="6" animated />
    </div>

    <template v-else>
      <!-- 基本信息卡片 -->
      <el-card class="profile-card" shadow="hover">
        <template #header>
          <div class="card-header">
            <div class="header-title">
              <el-icon><User /></el-icon>
              <span>基本信息</span>
            </div>
            <el-button
              v-if="!isEditing"
              type="primary"
              plain
              size="small"
              @click="startEdit"
            >
              <el-icon><Edit /></el-icon>
              编辑
            </el-button>
          </div>
        </template>

        <div v-if="isEditing" class="edit-form">
          <el-form :model="editForm" label-width="100px" :rules="rules" ref="formRef">
            <el-row :gutter="20">
              <el-col :span="12">
                <el-form-item label="姓名" prop="name">
                  <el-input
                    v-model="editForm.name"
                    placeholder="请输入姓名"
                  />
                </el-form-item>
              </el-col>
              <el-col :span="12">
                <el-form-item label="手机号码" prop="phone">
                  <el-input
                    v-model="editForm.phone"
                    placeholder="请输入手机号码"
                  />
                </el-form-item>
              </el-col>
            </el-row>
            <el-form-item label="邮箱" prop="email">
              <el-input
                v-model="editForm.email"
                type="email"
                placeholder="请输入邮箱地址"
              />
            </el-form-item>
            <el-form-item>
              <el-button type="primary" :loading="isSaving" @click="handleSave">
                <el-icon><Check /></el-icon>
                保存
              </el-button>
              <el-button @click="handleCancel">
                <el-icon><Close /></el-icon>
                取消
              </el-button>
            </el-form-item>
          </el-form>
        </div>

        <div v-else class="info-display">
          <el-row :gutter="40">
            <el-col :span="12" v-for="item in infoItems" :key="item.key">
              <div class="info-item">
                <div class="info-icon" :style="{ backgroundColor: item.bgColor }">
                  <el-icon :size="20" :color="item.iconColor">
                    <component :is="item.icon" />
                  </el-icon>
                </div>
                <div class="info-content">
                  <span class="info-label">{{ item.label }}</span>
                  <span class="info-value">{{ item.value || '-' }}</span>
                </div>
              </div>
            </el-col>
          </el-row>
        </div>
      </el-card>
    </template>
  </div>
</template>

<script setup>
import { ref, reactive, computed, onMounted } from 'vue'
import { ElMessage } from 'element-plus'
import {
  User,
  Edit,
  Check,
  Close,
  Message,
  Phone,
  Calendar
} from '@element-plus/icons-vue'
import { getUserInfo, updateUserInfo } from '@/api/jobseeker/profile'

// 加载状态
const isLoading = ref(false)
const isSaving = ref(false)
const isEditing = ref(false)
const formRef = ref(null)

// 用户信息
const userInfo = ref(null)

// 编辑表单
const editForm = reactive({
  name: '',
  phone: '',
  email: ''
})

// 表单验证规则
const rules = {
  name: [
    { required: true, message: '请输入姓名', trigger: 'blur' },
    { min: 2, max: 20, message: '姓名长度在 2 到 20 个字符', trigger: 'blur' }
  ],
  email: [
    { required: true, message: '请输入邮箱地址', trigger: 'blur' },
    { type: 'email', message: '请输入正确的邮箱地址', trigger: 'blur' }
  ],
  phone: [
    { pattern: /^1[3-9]\d{9}$/, message: '请输入正确的手机号码', trigger: 'blur' }
  ]
}

// 信息项配置
const infoItems = computed(() => [
  {
    key: 'name',
    label: '姓名',
    value: userInfo.value?.name,
    icon: 'User',
    bgColor: '#ecf5ff',
    iconColor: '#409eff'
  },
  {
    key: 'email',
    label: '邮箱',
    value: userInfo.value?.email,
    icon: 'Message',
    bgColor: '#f0f9ff',
    iconColor: '#10b981'
  },
  {
    key: 'phone',
    label: '手机号码',
    value: userInfo.value?.phone,
    icon: 'Phone',
    bgColor: '#f5f3ff',
    iconColor: '#8b5cf6'
  },
  {
    key: 'createdAt',
    label: '注册时间',
    value: userInfo.value?.createdAt
      ? new Date(userInfo.value.createdAt).toLocaleDateString('zh-CN')
      : '-',
    icon: 'Calendar',
    bgColor: '#fff7ed',
    iconColor: '#f97316'
  }
])

// 加载用户信息
const loadUserInfo = async () => {
  try {
    isLoading.value = true
    const res = await getUserInfo()
    userInfo.value = res.data || res
    // 同步编辑表单
    editForm.name = userInfo.value?.name || ''
    editForm.phone = userInfo.value?.phone || ''
    editForm.email = userInfo.value?.email || ''
  } catch (error) {
    ElMessage.error('加载用户信息失败')
    console.error(error)
  } finally {
    isLoading.value = false
  }
}

// 开始编辑
const startEdit = () => {
  if (userInfo.value) {
    editForm.name = userInfo.value.name || ''
    editForm.phone = userInfo.value.phone || ''
    editForm.email = userInfo.value.email || ''
  }
  isEditing.value = true
}

// 保存修改
const handleSave = async () => {
  // 表单验证
  if (!formRef.value) return

  try {
    await formRef.value.validate()
  } catch (error) {
    return
  }

  try {
    isSaving.value = true
    await updateUserInfo({
      name: editForm.name,
      phone: editForm.phone,
      email: editForm.email
    })
    ElMessage.success('个人信息更新成功')
    isEditing.value = false
    await loadUserInfo()
  } catch (error) {
    ElMessage.error(error.response?.data?.message || '更新失败，请重试')
    console.error(error)
  } finally {
    isSaving.value = false
  }
}

// 取消编辑
const handleCancel = () => {
  isEditing.value = false
  // 重置表单
  if (userInfo.value) {
    editForm.name = userInfo.value.name || ''
    editForm.phone = userInfo.value.phone || ''
    editForm.email = userInfo.value.email || ''
  }
}

onMounted(() => {
  loadUserInfo()
})
</script>

<style scoped lang="scss">
.profile-container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 20px;
}

.profile-header {
  margin-bottom: 24px;

  h1 {
    font-size: 28px;
    font-weight: 600;
    color: #1f2937;
    margin: 0 0 8px;
  }

  .subtitle {
    color: #6b7280;
    font-size: 14px;
    margin: 0;
  }
}

.loading-container {
  padding: 40px 0;
}

.profile-card {
  margin-bottom: 20px;
}

.card-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.header-title {
  display: flex;
  align-items: center;
  gap: 8px;
  font-weight: 600;
  font-size: 16px;

  .el-icon {
    font-size: 18px;
    color: #409eff;
  }
}

.edit-form {
  padding: 20px 0;
}

.info-display {
  padding: 20px 0;
}

.info-item {
  display: flex;
  align-items: center;
  gap: 16px;
  padding: 16px 0;
  border-bottom: 1px solid #f3f4f6;

  &:last-child {
    border-bottom: none;
  }
}

.info-icon {
  width: 48px;
  height: 48px;
  border-radius: 12px;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
}

.info-content {
  display: flex;
  flex-direction: column;
  gap: 4px;
  flex: 1;
  min-width: 0;
}

.info-label {
  font-size: 13px;
  color: #6b7280;
}

.info-value {
  font-size: 15px;
  font-weight: 500;
  color: #1f2937;
  word-break: break-all;
}

.security-list {
  padding: 10px 0;
}

.security-item {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 20px 0;
  border-bottom: 1px solid #f3f4f6;

  &:last-child {
    border-bottom: none;
  }
}

.security-info {
  display: flex;
  align-items: center;
  gap: 16px;
}

.security-icon {
  width: 48px;
  height: 48px;
  border-radius: 12px;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
}

.security-content {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.security-title {
  font-size: 15px;
  font-weight: 500;
  color: #1f2937;
}

.security-desc {
  font-size: 13px;
  color: #6b7280;
}

@media (max-width: 768px) {
  .profile-container {
    padding: 16px;
  }

  .profile-header h1 {
    font-size: 24px;
  }

  .info-item {
    flex-direction: column;
    align-items: flex-start;
    gap: 12px;
  }

  .security-item {
    flex-direction: column;
    align-items: flex-start;
    gap: 16px;
  }

  .security-info {
    width: 100%;
  }
}
</style>
